# Generated by Django 5.2.5 on 2025-09-05 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Entreprise"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        help_text="Formats acceptés: PDF, DOC, DOCX (max 5MB)",
                        upload_to="cvs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="CV",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Demande commerciale"),
                            ("candidature", "Candidature"),
                            ("information", "Demande d'information"),
                            ("autre", "Autre"),
                        ],
                        default="information",
                        max_length=20,
                        verbose_name="Type de contact",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("read", "Lu"),
                            ("replied", "Répondu"),
                            ("archived", "Archivé"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "description_fr",
                    models.TextField(verbose_name="Description (Français)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Description (Anglais)"),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Lieu")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("stage", "Stage"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=50,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salaire minimum"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Salaire maximum"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publiée"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date limite de candidature"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL de la page (ex: accueil, a-propos)",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "content_fr",
                    models.TextField(blank=True, verbose_name="Contenu (Français)"),
                ),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Contenu (Anglais)"),
                ),
                (
                    "meta_description_fr",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Meta Description (Français)",
                    ),
                ),
                (
                    "meta_description_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Meta Description (Anglais)",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image principale de la page",
                        upload_to="pages/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "menu_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage dans le menu principal",
                        verbose_name="Ordre dans le menu",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publiée"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["menu_order", "title_fr"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("company_address", models.TextField(verbose_name="Adresse")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Email qui recevra les messages du formulaire de contact",
                        max_length=254,
                        verbose_name="Email pour les contacts",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="config/", verbose_name="Logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configurations du site",
            },
        ),
    ]
